dist: trusty
sudo: off
language: python
services:
  - docker
addons:
  apt:
    packages:
      - libssl-dev
      - libffi-dev
      - python-dev
install: echo 'skip'
cache: pip
jobs:
  include:
    - stage: precheck
      env: PURPOSE='PEP8'
      script: ./scripts/ci/precheck_pep8.sh
      python: 3.6
    - stage: precheck
      env: PURPOSE='Headers'
      script: ./scripts/ci/precheck_header.sh
      python: 3.6
    - stage: publish
      script: ./scripts/ci/build_droid.sh
      python: 3.6
      env: PURPOSE='Automation Docker'
      if: repo = Azure/azure-cli and type = push
